language: python
python:
    - 2.7
    - 3.4
notifications:
  email: false

services:
  - postgresql
addons:
  postgresql: "9.4"
install:
- pip install -r requirements_dev.txt
script: py.test -vvv -s --cov=timechop
after_success: codecov
