language: python
python: 3.4
notifications:
    email: false
before_install:
- sudo apt-get update
- sudo apt-get install libhdf5-serial-dev
install:
- pip install -r requirements_dev.txt
script: py.test --cov=architect
after_success: codecov
