language: python
python: 3.4
notifications:
    email: false
services:
      - postgresql
addons:
    postgresql: "9.4"
install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
script: py.test -vvv
deploy:
  password:
    secure: bOkUuUXzfLtCXZtNP8QNUQe2Gg2Q0vV653hBH/urYJzLr3RxPy/ideI6qHigDatDgCrk1GTO6Y1a51hwUUvHBzDvUIYm38wgjkIjtIRztqemQGl6b59Hgf797W7jjPfmryrg/XTdpCmwy7ThV0tV8rhkgg7+o63XN8XouJ5tbYdkQvIrGSL1y0yp6RWniMLGHJ2ZeFIe/g+I04IGJFCEfeNBpIe4rL6dFknV/ruQ8fUshW+Hb5M6DZp90nu5c8rdP17ji+4BBrROUn9EeGYSfudJt38V8SKQkawhMGx6+FQzpLO2gZC6p5TlCFM3iK7wmAYbHxMeJ6z58TSwT3J+8aYRlbYWpBknZYQdL7WhTtHgiL/ZRRlVAxPlCzDreHYjItGp41CxS2sjAwQazuLoqrzYsKOsHQUEYkhYTTr8arX+cz0s7zB0kyNA8a4i2hNhl8MHmTovlbd9cgTWSkz6+kGJAr0HIfjWjoLVH/WwBSRv/ALAoUe3OatQ2WxxLQHjoXI+jt0fL2BA0+JdXHVyCYteD4YwJs1fp1LjbC/l0TDZjKgJsljTQWUuiJq5IzeHRwrqsoHlSQ9hns9AyltPfgbn3QdovBCwKlfP5KUqNFtNG3CUxfwZXMpOHls5YeKnTV7CkpNPOxqTaYFsSurUmJ+Xfkk+YLlf6rKsRq3wPIY=
  provider: pypi
  true:
    tags: true
    repo: dssg/results-schema
  distributions: sdist bdist_wheel
  user: dssg
