site_name: Triage Documentation
theme: bootstrap
docs_dir: sources
repo_url: http://github.com/dssg/triage
edit_uri: blob/master/docs/templates
site_description: 'Documentation for Triage.'


pages:
  - Home: index.md
  - Writing an Experiment: writing-an-experiment.md
    - Feature Examples: feature-examples.md
  - Experiment Procedure: experiment-details.md
    - Timechop Code Dive: time-chop-deep-dive.md
    - Collate Code Dive: collate-deep-dive.md
  - Experiment Architecture: experiment-architecture.md
  - API Docs:
    - ExperimentBase: triage.experiments.base.md
    - SingleThreadedExperiment: triage.experiments.singlethreaded.md
    - MultiCoreExperiment: triage.experiments.multicore.md
